package exercicioSemana06;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class InterfaceConsultar extends JPanel {
  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
private JButton btnConsultar;
  private JLabel lblCodigo;
  private JLabel lblDescrição;
  private JLabel lblPreço;
  private JLabel lblQuantidadeEmEstoque;
  private JTextField tfCodigo;
  private JTextField tfDescricao;
  private JTextField tfPreco;
  private JTextField tfEstoque;
  private JButton btnVoltar;
  private Produto produto = new Produto();
  

  public InterfaceConsultar() {
      //construct components
      btnConsultar = new JButton ("Consultar");
      lblCodigo = new JLabel ("Código ");
      lblDescrição = new JLabel ("Descrição");
      lblPreço = new JLabel ("Preço");
      lblQuantidadeEmEstoque = new JLabel ("Estoque");
      tfCodigo = new JTextField (5);
      tfDescricao = new JTextField (5);
      tfPreco = new JTextField (5);
      tfEstoque = new JTextField (5);
      btnVoltar = new JButton ("Voltar");

      //adjust size and set layout
      setPreferredSize (new Dimension (944, 581));
      setLayout (null);
      
      //set components properties
      tfDescricao.setEnabled (false);
      tfPreco.setEnabled (false);
      tfEstoque.setEnabled (false);

      //add components
      add (btnConsultar);
      add (lblCodigo);
      add (lblDescrição);
      add (lblPreço);
      add (lblQuantidadeEmEstoque);
      add (tfCodigo);
      add (tfDescricao);
      add (tfPreco);
      add (tfEstoque);
      add (btnVoltar);

      //set component bounds (only needed by Absolute Positioning)
      btnConsultar.setBounds (330, 285, 265, 55);
      lblCodigo.setBounds (190, 85, 100, 25);
      lblDescrição.setBounds (190, 120, 100, 25);
      lblPreço.setBounds (190, 160, 100, 25);
      lblQuantidadeEmEstoque.setBounds (190, 200, 100, 25);
      tfCodigo.setBounds (250, 80, 450, 30);
      tfDescricao.setBounds (250, 120, 450, 30);
      tfPreco.setBounds (250, 160, 450, 30);
      tfEstoque.setBounds (250, 200, 450, 30);
      btnVoltar.setBounds (330, 370, 265, 55);
      
      //Muda de tela para menu de Opções
      btnVoltar.addActionListener(new ActionListener() {
    	  public void actionPerformed(ActionEvent e) {
    		   JFrame menuOpcoes = new JFrame ("MyPanel");
    		   menuOpcoes.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    		   menuOpcoes.getContentPane().add (new MenuOpcoes());
    		   menuOpcoes.pack();
    		   menuOpcoes.setVisible (true);
    	  }
      });
      
      
      btnConsultar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					
					int idPesquisa = Integer.parseInt(tfCodigo.getText());					
					Produto produto1 = produto.ler(idPesquisa);					
				
					if(produto1 != null) {			
						String codigo = "" + produto1.getCodigo();
						String descricao = produto1.getDescricao();
						String preco = "" + produto1.getValor();
						String quantidade = "" + produto1.getQuantidadeEstoque();		
						tfDescricao.setText(descricao);
						tfPreco.setText(preco);
						tfEstoque.setText(quantidade);
					} 
					else {
						JOptionPane.showMessageDialog(null, "Produto não encontrado");
						tfCodigo.setText("");
						tfDescricao.setText("");
						tfPreco.setText("");
						tfEstoque.setText("");	
					}					
					
					} catch (Exception erro) {
						System.out.println("Erro " + erro);
					}
					
			}
		});
  }


  public static void main (String[] args) {
      JFrame frame = new JFrame ("MyPanel");
      frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
      frame.getContentPane().add (new InterfaceConsultar());
      frame.pack();
      frame.setVisible (true);
  }
}
