package exercicioSemana06;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class InterfaceCadastrar extends JPanel {
  private JButton btnCadastrarNovoCliente;
  private JLabel lblCodigo;
  private JLabel lblDescrição;
  private JLabel lblPreço;
  private JLabel lblQuantidadeEmEstoque;
  private JTextField tfCodigo;
  private JTextField tfDescricao;
  private JTextField tfPreco;
  private JTextField tfEstoque;
  private JButton btnVoltar;
  private Produto produto = new Produto();

  public InterfaceCadastrar() {
      //construct components
      btnCadastrarNovoCliente = new JButton ("Cadastrar");
      lblCodigo = new JLabel ("Código ");
      lblDescrição = new JLabel ("Descrição");
      lblPreço = new JLabel ("Preço");
      lblQuantidadeEmEstoque = new JLabel ("Estoque");
      tfCodigo = new JTextField (5);
      tfDescricao = new JTextField (5);
      tfPreco = new JTextField (5);
      tfEstoque = new JTextField (5);
      btnVoltar = new JButton ("Voltar");

      //adjust size and set layout
      setPreferredSize (new Dimension (944, 581));
      setLayout (null);

      //add components
      add (btnCadastrarNovoCliente);
      add (lblCodigo);
      add (lblDescrição);
      add (lblPreço);
      add (lblQuantidadeEmEstoque);
      add (tfCodigo);
      add (tfDescricao);
      add (tfPreco);
      add (tfEstoque);
      add (btnVoltar);

      //set component bounds (only needed by Absolute Positioning)
      btnCadastrarNovoCliente.setBounds (330, 285, 265, 55);
      lblCodigo.setBounds (190, 85, 100, 25);
      lblDescrição.setBounds (190, 120, 100, 25);
      lblPreço.setBounds (190, 160, 100, 25);
      lblQuantidadeEmEstoque.setBounds (190, 200, 100, 25);
      tfCodigo.setBounds (250, 80, 450, 30);
      tfDescricao.setBounds (250, 120, 450, 30);
      tfPreco.setBounds (250, 160, 450, 30);
      tfEstoque.setBounds (250, 200, 450, 30);
      btnVoltar.setBounds (330, 370, 265, 55);
      
      //Muda de tela para menu de Opções
      btnVoltar.addActionListener(new ActionListener() {
    	  public void actionPerformed(ActionEvent e) {
    		   JFrame menuOpcoes = new JFrame ("MyPanel");
    		   menuOpcoes.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    		   menuOpcoes.getContentPane().add (new MenuOpcoes());
    		   menuOpcoes.pack();
    		   menuOpcoes.setVisible (true);
    	  }
      });

      
      btnCadastrarNovoCliente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					produto.setCodigo(Integer.parseInt(tfCodigo.getText()));
					produto.setDescricao(tfDescricao.getText());
					produto.setValor(Double.parseDouble(tfPreco.getText()));
					produto.setQuantidadeEstoque(Integer.parseInt(tfEstoque.getText()));
					JOptionPane.showMessageDialog(btnCadastrarNovoCliente, produto.gravar());
					tfCodigo.setText("");
					tfDescricao.setText("");
					tfPreco.setText("");
					tfEstoque.setText("");
				} catch (Exception e2) {
					JOptionPane.showMessageDialog(null, "Ops Ocorreu um erro verifique os dados informados\n"+e2+
							"\n O campo código e estoque só aceita numeros inteiro"
							+ "\n e o campo valor só aceita valores inteiros/e valores com casa decima utilizando o ponto(.) em vez da virgula(,) ");
				}
			}
		});
  }


  public static void main (String[] args) {
      JFrame frame = new JFrame ("MyPanel");
      frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
      frame.getContentPane().add (new InterfaceCadastrar());
      frame.pack();
      frame.setVisible (true);
  }
}
