package exercicioSemana06;
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MenuOpcoes extends JPanel {
  private JButton btnCadastrar;
  private JButton btnConsultar;
  private JLabel lblSaudacao;

  public MenuOpcoes() {
      //construct components
	  btnCadastrar = new JButton ("Cadastrar Produto");
	  btnConsultar = new JButton ("Consultar Produto");
      lblSaudacao = new JLabel ("Bem vindo ao sistema de produtos");

      //adjust size and set layout
      setPreferredSize (new Dimension (944, 581));
      setLayout (null);

      //add components
      add (btnCadastrar);
      add (btnConsultar);
      add (lblSaudacao);

      //set component bounds (only needed by Absolute Positioning)
      btnCadastrar.setBounds (335, 210, 225, 60);
      btnConsultar.setBounds (335, 300, 225, 60);
      lblSaudacao.setBounds (350, 145, 200, 45);
      
      
   
      
      //Muda de tela para cadastrar
      btnCadastrar.addActionListener(new ActionListener() {
    	  public void actionPerformed(ActionEvent e) {
    		   JFrame interfaceCadastrar = new JFrame ("MyPanel");
			   interfaceCadastrar.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
			   interfaceCadastrar.getContentPane().add (new InterfaceCadastrar());
			   interfaceCadastrar.pack();
			   interfaceCadastrar.setVisible (true);
    	  }
      });
      
      //Muda de tela para consultar
      btnConsultar.addActionListener(new ActionListener() {
    	  public void actionPerformed(ActionEvent e) {
    		   JFrame interfaceConsultar = new JFrame ("MyPanel");
    		   interfaceConsultar.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    		   interfaceConsultar.getContentPane().add (new InterfaceConsultar());
    		   interfaceConsultar.pack();
    		   interfaceConsultar.setVisible (true);
    	  }
      });
  }
  
  


  public static void main (String[] args) {
      JFrame frame = new JFrame ("Menu de Opções");
      frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
      frame.getContentPane().add (new MenuOpcoes());
      frame.pack();
      frame.setVisible (true);
  }
}
